name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: TypeScript Container Action Template
      uses: kevinpollet/typescript-container-action-template@v1
      with:
        # Name to greet
        name: Sunbase
    - name: Typescript compiler
      uses: iCrawl/action-tsc@v1
      with:
        name: Sunbase
