name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - name: Typescript compiler
      uses: iCrawl/action-tsc@v1
      with:
        name: Sunbase
